### ISSUE TITLE
Spurious StoreProhibitedCause panic on reconnection (CA-106)

### ISSUE THREAD

**Issue by benpeoples** [espressif/esp-google-iot#20]
I don't have a lot of detail here, I think I mostly want to see if other people are having this issue and/or have more details.

This is the complete task we're running, based on the esp-google-iot example:

Code here: https://gist.github.com/benpeoples/4f36b1818dbc44e74aa4cd18cba51817

Randomly, this task will trigger a StoreProhibitedCause panic.    We established this morning that this is happening upon a reconnection-- specifically the "random" nature had to do with Google kicking us off servers as they were being shutdown/rebooted: we established this in the Google IOT Core logs.   It does not happen every time the server reconnects (or we'd be seeing it every 86400 seconds), and we had two controllers panic this morning when a server shut down, but a third did not.   The other controllers in the system did not have a server disconnection.

Unfortunately, I do not know precisely where (other than in this task posted above) the panic happened, this is the relevant bit from the core dump (we're saving core dumps to flash and then shipping them upon reboot): 

`==================== CURRENT THREAD STACK =====================
#0  0x400871d8 in invoke_abort () at /Users/benpeoples/esp/esp-idf-v4.1/components/esp32/panic.c:159
#1  0x400875f4 in abort () at /Users/benpeoples/esp/esp-idf-v4.1/components/esp32/panic.c:174
Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

I don't see anything obvious I'm doing wrong, so I'm thinking some part of the iotc_delete_context or iotc_shutdown is not reliably cleaning everything up?

**Comment by LeandroVanolli** [comment]
Hello @benpeoples !

I'm using this sdk and sometimes when the connection closes, the panic message appears. Reading the next lines, I found out that the `free(subscribe_topic_command);` and `free(subscribe_topic_config);` were crashing the esp because sometimes the "on_state_changed" callback is called twice, causing reentrance on free function and corrupting heap. My workaround was to stop calling free function. Due to this, the subscribe variables are hardcoded. It solved my crashing problem.

**Comment by benpeoples** [comment]
Excellent!   We've since moved on to just using MQTT directly (the SDK does not do a *lot* vs. just MQTT), but this is excellent news that you've found the culprit!

**Comment by LeandroVanolli** [comment]
Intersting... Now I'm facing a problem that I reported on #26 . I don't know how to decode the message the callback receive from the server when I publish something. Did you manage to do it?

**Comment by benpeoples** [comment]
Sorry, we're 100% at QOS 0 so I'm not looking at server responses

**Comment by abrender** [comment]
I've narrowed down the scenario in which `free` causes an abort/panic by being called twice in `on_connection_state_changed`.

I added logging of both `conn_data->connection_state` and `state`. Indeed there can be two calls to `on_connection_state_changed` in a row with `conn_data->connection-state == IOTC_CONNECTION_STATE_CLOSED` when a reconnect fails after a disconnect (each with a different iotc_state).

Here's the order of calls that I saw:

| conn_data->connection_state ([iotc_connection_state_t](https://proppy.github.io/iot-device-sdk-embedded-c/doxygen/api/html/d9/df6/iotc__connection__data_8h_source.html#l00031))  | state ([iotc_state_t](https://proppy.github.io/iot-device-sdk-embedded-c/doxygen/api/html/d4/d7c/iotc__error_8h_source.html#l00030)) | Note
| ------------- | ------------- | ------------- |
| IOTC_CONNECTION_STATE_OPENED  |  IOTC_STATE_OK  | subscribe_topic_command allocated
| IOTC_CONNECTION_STATE_CLOSED | IOTC_CONNECTION_RESET_BY_PEER_ERROR  | subscribe_topic_command `free`d
| IOTC_CONNECTION_STATE_OPENED  |  IOTC_STATE_OK  | subscribe_topic_command allocated
| IOTC_CONNECTION_STATE_CLOSED | IOTC_CONNECTION_RESET_BY_PEER_ERROR  | subscribe_topic_command `free`d
| IOTC_CONNECTION_STATE_OPENED  |  IOTC_STATE_OK  | subscribe_topic_command allocated
| IOTC_CONNECTION_STATE_CLOSED | IOTC_CONNECTION_RESET_BY_PEER_ERROR  | subscribe_topic_command `free`d
| IOTC_CONNECTION_STATE_CLOSED | IOTC_STATE_TIMEOUT | subscribe_topic_command `free`d **again**. panic/abort ensue.

**Comment by benpeoples** [comment]
So would the minimum patch to be to check-if-null-before-free when IOTC_STATE_TIMEOUT?

**Comment by abrender** [comment]
I'd hestitate to recommend placing a check based on IOTC_STATE_TIMEOUT, because [iotc_state_t](https://proppy.github.io/iot-device-sdk-embedded-c/doxygen/api/html/d4/d7c/iotc__error_8h_source.html#l00030) actually has >70 states, so it'd be very difficult to start enumerating and special casing individual states.

We can set the pointer to NULL after `free` is called, that is a defense-in-depth against the dangling pointer... but I'm concerned that the subsequent code might have similar problems even if we get past the `free` code - is it safe to call the rest of the code for a second time in a row?

I'll update my local code to set the two pointers to NULL after `free`ing them and report back in a few days if things live happily-ever-after.

**Comment by abrender** [comment]
I've confirmed that freeing the memory does solve the crash/abort/panic/reboot.

I'm submitting a pull request with the fix (https://github.com/espressif/esp-google-iot/pull/34).
